server:
  port: 8001

spring:
  application:
    name: cloud-system-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.128:3306/springcloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: admin
    password: Wzm123456!

eureka:
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 是否从urekaServer抓取自己的注册信息，默认为true。单节点无所谓，集群必须配置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #逗号隔开配置集群
  instance:
    instance-id: system
    ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzm.entity

