server:
  port: 8001

spring:
  application:
    name: cloud-system-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.128:3306/springcloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: admin
    password: Wzm123456!

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzm.entity
